### ISSUE TITLE
Not compatible with 1.12.2

### ISSUE THREAD

**Issue by Herobrine2143** [LlamaLad7/Better-Chat#12]
In the website of Modrinth it states that the mod is compatible with 1.12.2 but when I try it, it tells me that it only works for 1.8.9

![image](https://user-images.githubusercontent.com/22053132/134807106-5ab4dbe1-25a1-457e-8ded-0cfc883e5f60.png)

if you need the log, it's here:

[https://pastebin.com/MyuwrRYv](url)

**Comment by LlamaLad7** [comment]
There are separate jars for 1.8.9 and 1.12.2. You downloaded the 1.8.9 jar. Both can be found here: https://modrinth.com/mod/betterchat/version/IuawESzw

**Comment by Herobrine2143** [comment]
My bad, I just clicked on the download icon without actually clicking on the mod. Just through the "versions" page.
