### ISSUE TITLE
crash while launching a server

### ISSUE THREAD

**Issue by Zack7292** [LlamaLad7/Better-Chat#3]
Hey, when i was launching a pack on a server (to experiment the server side) it crash (here's a mediafire link of the pack: https://www.mediafire.com/file/5qoqw0e5ujt009u/infex_serv_.zip/file )
here the crash log: https://pastebin.com/QAXgsXph

**Comment by LlamaLad7** [comment]
Hmm. I'm quite busy with schoolwork at the moment, but I'll take a look at that in a couple of weeks! Thanks for reporting it!

**Comment by LlamaLad7** [comment]
Although why would you even use this mod on a server. There is no chat GUI on a server

**Comment by Zack7292** [comment]
well it was my issue lol its actually a client side mod srry my bad (ngl i've forgot this thing)
