### ISSUE TITLE
Strange behaivor with clickable elements

### ISSUE THREAD

**Issue by jkroepke** [LlamaLad7/Better-Chat#5]
If I enable BetterChat, I can't click on hyperlink directly anymore. I have to click 2 lines below to 'click' on the hyperlink. It looks like the visible text and the clickable hyperlink box are different

w/o Better Chat: https://i.imgur.com/DceMeBg.png

w/ Better Chat: https://i.imgur.com/1getk8F.png (note here, If I hover over the hyperlink like above, nothing happens)

**Comment by jkroepke** [comment]
Maybe there is a conflict with https://sk1er.club/mods/patcher

**Comment by jkroepke** [comment]
Yep, it's this option:

https://i.imgur.com/n8iI6P1.png

**Comment by LlamaLad7** [comment]
I've known this for a long time given I am one of the devs on patcher.
Just disable that and move the chat in betterchat instead

**Comment by jkroepke** [comment]
@LlamaLad7 

>  I am one of the devs on patcher.

Do is there a public issue tracker available? I would like to report a error and a feature request.

**Comment by LlamaLad7** [comment]
Join the discord: https://discord.gg/sk1er
